import fs from 'fs';
import path from 'path';

const services = [
  { name: "Custom Business Website", slug: "custom-business-website", cat: "Web Development", tier: "1" },
  { name: "WordPress Website", slug: "wordpress-website", cat: "Web Development", tier: "1" },
  { name: "React.js Web App", slug: "reactjs-web-app", cat: "Web Development", tier: "1" },
  { name: "Next.js Website", slug: "nextjs-website", cat: "Web Development", tier: "1" },
  { name: "Portfolio Website", slug: "portfolio-website", cat: "Web Development", tier: "2" },
  { name: "Corporate Website", slug: "corporate-website", cat: "Web Development", tier: "1" },
  { name: "Nonprofit Website", slug: "nonprofit-website", cat: "Web Development", tier: "2" },
  { name: "Restaurant Website", slug: "restaurant-website", cat: "Web Development", tier: "2" },
  { name: "Real Estate Website", slug: "real-estate-website", cat: "Web Development", tier: "1" },
  { name: "Clinic Website", slug: "clinic-website", cat: "Web Development", tier: "2" },
  { name: "School/Academy Website", slug: "school-academy-website", cat: "Web Development", tier: "2" },
  { name: "Law Firm Website", slug: "law-firm-website", cat: "Web Development", tier: "1" },
  { name: "Construction Website", slug: "construction-website", cat: "Web Development", tier: "2" },
  { name: "Salon & Spa Website", slug: "salon-spa-website", cat: "Web Development", tier: "2" },
  { name: "Hotel Website", slug: "hotel-website", cat: "Web Development", tier: "2" },
  { name: "Event Management Website", slug: "event-management-website", cat: "Web Development", tier: "2" },
  { name: "Photography Website", slug: "photography-website", cat: "Web Development", tier: "2" },
  { name: "Consulting Website", slug: "consulting-website", cat: "Web Development", tier: "1" },
  { name: "Multilingual Website", slug: "multilingual-website", cat: "Web Development", tier: "2" },
  { name: "Website Redesign", slug: "website-redesign", cat: "Web Development", tier: "1" },
  { name: "Sales Landing Page", slug: "sales-landing-page", cat: "Landing Pages", tier: "1" },
  { name: "Lead Gen Landing Page", slug: "lead-gen-landing-page", cat: "Landing Pages", tier: "1" },
  { name: "Webinar Registration", slug: "webinar-registration-page", cat: "Landing Pages", tier: "2" },
  { name: "Product Launch Page", slug: "product-launch-page", cat: "Landing Pages", tier: "1" },
  { name: "App Download Page", slug: "app-download-page", cat: "Landing Pages", tier: "2" },
  { name: "Coming Soon Page", slug: "coming-soon-page", cat: "Landing Pages", tier: "3" },
  { name: "Sales Funnel Build", slug: "sales-funnel-build", cat: "Landing Pages", tier: "1" },
  { name: "Thank You Page Design", slug: "thank-you-page-design", cat: "Landing Pages", tier: "3" },
  { name: "Squeeze Page", slug: "squeeze-page", cat: "Landing Pages", tier: "2" },
  { name: "Upsell/Downsell Page", slug: "upsell-downsell-page", cat: "Landing Pages", tier: "3" },
  { name: "WooCommerce Store", slug: "woocommerce-store", cat: "E-Commerce", tier: "1" },
  { name: "Shopify Store", slug: "shopify-store", cat: "E-Commerce", tier: "1" },
  { name: "Custom E-commerce Site", slug: "custom-ecommerce-site", cat: "E-Commerce", tier: "1" },
  { name: "E-commerce SEO", slug: "ecommerce-seo", cat: "E-Commerce", tier: "1" },
  { name: "Product Page Optimization", slug: "product-page-optimization", cat: "E-Commerce", tier: "2" },
  { name: "Payment Gateway Setup", slug: "payment-gateway-setup", cat: "E-Commerce", tier: "3" },
  { name: "Abandoned Cart Recovery", slug: "abandoned-cart-recovery", cat: "E-Commerce", tier: "2" },
  { name: "Multi-vendor Marketplace", slug: "multi-vendor-marketplace", cat: "E-Commerce", tier: "1" },
  { name: "Subscription Box Site", slug: "subscription-box-site", cat: "E-Commerce", tier: "2" },
  { name: "Digital Products Store", slug: "digital-products-store", cat: "E-Commerce", tier: "2" },
  { name: "AI Chatbot", slug: "ai-chatbot", cat: "Automation & AI", tier: "1" },
  { name: "WhatsApp Automation", slug: "whatsapp-automation", cat: "Automation & AI", tier: "1" },
  { name: "CRM Automation", slug: "crm-automation", cat: "Automation & AI", tier: "1" },
  { name: "Email Automation", slug: "email-automation", cat: "Automation & AI", tier: "1" },
  { name: "Lead Capture Automation", slug: "lead-capture-automation", cat: "Automation & AI", tier: "1" },
  { name: "AI Content Writer Setup", slug: "ai-content-writer", cat: "Automation & AI", tier: "2" },
  { name: "Zapier/Make Workflows", slug: "zapier-make-workflows", cat: "Automation & AI", tier: "2" },
  { name: "AI SEO Integration", slug: "ai-seo-integration", cat: "Automation & AI", tier: "2" },
  { name: "Booking & Appointment Bot", slug: "booking-bot", cat: "Automation & AI", tier: "2" },
  { name: "Invoice Automation", slug: "invoice-automation", cat: "Automation & AI", tier: "2" },
  { name: "Social Media Auto-Post", slug: "social-media-autopost", cat: "Automation & AI", tier: "2" },
  { name: "AI Product Recommender", slug: "ai-product-recommender", cat: "Automation & AI", tier: "2" },
  { name: "Customer Feedback AI", slug: "customer-feedback-ai", cat: "Automation & AI", tier: "2" },
  { name: "AI Analytics Dashboard", slug: "ai-analytics-dashboard", cat: "Automation & AI", tier: "1" },
  { name: "HR Automation", slug: "hr-automation", cat: "Automation & AI", tier: "2" },
  { name: "SEO Optimization", slug: "seo-optimization", cat: "Marketing & SEO", tier: "1" },
  { name: "Local SEO", slug: "local-seo", cat: "Marketing & SEO", tier: "1" },
  { name: "Technical SEO Audit", slug: "technical-seo-audit", cat: "Marketing & SEO", tier: "1" },
  { name: "Content Marketing", slug: "content-marketing", cat: "Marketing & SEO", tier: "1" },
  { name: "Google Ads", slug: "google-ads", cat: "Marketing & SEO", tier: "1" },
  { name: "Facebook/Meta Ads", slug: "facebook-meta-ads", cat: "Marketing & SEO", tier: "1" },
  { name: "Social Media Management", slug: "social-media-management", cat: "Marketing & SEO", tier: "2" },
  { name: "Email Campaigns", slug: "email-campaigns", cat: "Marketing & SEO", tier: "2" },
  { name: "Video Marketing Page", slug: "video-marketing-page", cat: "Marketing & SEO", tier: "2" },
  { name: "LinkedIn Lead Gen", slug: "linkedin-lead-gen", cat: "Marketing & SEO", tier: "1" },
  { name: "Google My Business", slug: "google-my-business", cat: "Marketing & SEO", tier: "2" },
  { name: "Reputation Management", slug: "reputation-management", cat: "Marketing & SEO", tier: "2" },
  { name: "Influencer Strategy", slug: "influencer-strategy", cat: "Marketing & SEO", tier: "2" },
  { name: "Affiliate Marketing Setup", slug: "affiliate-marketing-setup", cat: "Marketing & SEO", tier: "2" },
  { name: "Conversion Rate Optim.", slug: "cro", cat: "Marketing & SEO", tier: "1" },
  { name: "Custom CRM", slug: "custom-crm", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "SaaS MVP", slug: "saas-mvp", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "Admin Dashboard", slug: "admin-dashboard", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "API Integration", slug: "api-integration", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "Custom Plugin Dev", slug: "custom-plugin", cat: "SaaS & Custom Tools", tier: "2" },
  { name: "Online Booking System", slug: "online-booking", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "Membership Portal", slug: "membership-portal", cat: "SaaS & Custom Tools", tier: "2" },
  { name: "LMS Development", slug: "lms-development", cat: "SaaS & Custom Tools", tier: "1" },
  { name: "Job Board Site", slug: "job-board", cat: "SaaS & Custom Tools", tier: "2" },
  { name: "Directory Website", slug: "directory-website", cat: "SaaS & Custom Tools", tier: "2" },
  { name: "WordPress Maintenance", slug: "wordpress-maintenance", cat: "Maintenance & Support", tier: "2" },
  { name: "Speed Optimization", slug: "speed-optimization", cat: "Maintenance & Support", tier: "1" },
  { name: "Security & Malware", slug: "security-malware", cat: "Maintenance & Support", tier: "2" },
  { name: "Website Backup", slug: "website-backup", cat: "Maintenance & Support", tier: "3" },
  { name: "SSL Setup", slug: "ssl-setup", cat: "Maintenance & Support", tier: "3" },
  { name: "Website Migration", slug: "website-migration", cat: "Maintenance & Support", tier: "2" },
  { name: "Bug Fixing", slug: "bug-fixing", cat: "Maintenance & Support", tier: "2" },
  { name: "Performance Monitoring", slug: "performance-monitoring", cat: "Maintenance & Support", tier: "2" },
  { name: "Hosting Setup", slug: "hosting-setup", cat: "Maintenance & Support", tier: "3" },
  { name: "Domain & DNS Setup", slug: "domain-dns-setup", cat: "Maintenance & Support", tier: "3" },
  { name: "UI/UX Design", slug: "ui-ux-design", cat: "Design & Branding", tier: "1" },
  { name: "Brand Identity", slug: "brand-identity", cat: "Design & Branding", tier: "1" },
  { name: "Logo Design", slug: "logo-design", cat: "Design & Branding", tier: "1" },
  { name: "Figma Prototype", slug: "figma-prototype", cat: "Design & Branding", tier: "1" },
  { name: "Pitch Deck Design", slug: "pitch-deck-design", cat: "Design & Branding", tier: "2" },
  { name: "Social Media Graphics", slug: "social-media-graphics", cat: "Design & Branding", tier: "2" },
  { name: "Email Template Design", slug: "email-template-design", cat: "Design & Branding", tier: "2" },
  { name: "Infographic Design", slug: "infographic-design", cat: "Design & Branding", tier: "2" },
  { name: "Canva Brand Kit", slug: "canva-brand-kit", cat: "Design & Branding", tier: "3" },
];

const generateData = () => {
  const fullData = services.map(s => {
    return {
      slug: s.slug,
      SERVICE_NAME: s.name,
      SERVICE_TIER: s.tier,
      CATEGORY: s.cat,
      HERO_HEADLINE: "Professional " + s.name + " for Your Business",
      HERO_SUB: "Scale your brand with expert " + s.name + " services tailored for the Indian market.",
      PROBLEM_1_TITLE: "Stagnant Growth",
      PROBLEM_1_DESC: "Without professional " + s.name + ", your business is missing out on massive growth opportunities.",
      PROBLEM_2_TITLE: "Technical Hurdles",
      PROBLEM_2_DESC: "Dealing with complex technical setups can be frustrating and time-consuming.",
      PROBLEM_3_TITLE: "Low Conversion",
      PROBLEM_3_DESC: "Generic solutions fail to convert visitors into loyal customers.",
      SOLUTION_1_TITLE: "Expert Implementation",
      SOLUTION_1_DESC: "We handle the entire " + s.name + " process with precision and care.",
      SOLUTION_2_TITLE: "Custom Strategy",
      SOLUTION_2_DESC: "Every business is unique. We build solutions that fit your specific needs.",
      SOLUTION_3_TITLE: "Proven Results",
      SOLUTION_3_DESC: "Our methods are tested and proven to deliver measurable ROI.",
      STEP_1_TITLE: "Consultation", "STEP_1_DESC": "Understanding your unique business requirements.",
      STEP_2_TITLE: "Planning", "STEP_2_DESC": "Creating a detailed roadmap for success.",
      STEP_3_TITLE: "Execution", "STEP_3_DESC": "Our experts build your solution with clean code.",
      STEP_4_TITLE: "Review", "STEP_4_DESC": "Rigorous testing to ensure everything is perfect.",
      STEP_5_TITLE: "Optimization", "STEP_5_DESC": "Fine-tuning for maximum performance and speed.",
      STEP_6_TITLE: "Launch", "STEP_6_DESC": "Going live and starting your growth journey.",
      WEEK_1_MILESTONE: "Discovery", "WEEK_1_DELIVERABLE": "Project Brief",
      WEEK_2_MILESTONE: "Design", "WEEK_2_DELIVERABLE": "Visual Mockups",
      WEEK_3_MILESTONE: "Build", "WEEK_3_DELIVERABLE": "Beta Version",
      WEEK_4_MILESTONE: "Launch", "WEEK_4_DELIVERABLE": "Final Delivery",
      FEATURE_1: "Custom Design", "FEATURE_2": "Mobile Optimized", "FEATURE_3": "SEO Friendly", "FEATURE_4": "Fast Loading", "FEATURE_5": "Secure Setup", "FEATURE_6": "WhatsApp Support", "FEATURE_7": "Analytics Integration", "FEATURE_8": "Cloud Hosting", "FEATURE_9": "1 Month Support", "FEATURE_10": "Training Included",
      PORTFOLIO_IMG_1: "https://picsum.photos/seed/" + s.slug + "1/800/600", "PORTFOLIO_LABEL_1": s.name + " Project Alpha",
      PORTFOLIO_IMG_2: "https://picsum.photos/seed/" + s.slug + "2/800/600", "PORTFOLIO_LABEL_2": s.name + " Project Beta",
      PORTFOLIO_IMG_3: "https://picsum.photos/seed/" + s.slug + "3/800/600", "PORTFOLIO_LABEL_3": s.name + " Project Gamma",
      RELATED_SERVICE_1: "SEO Optimization", "RELATED_SERVICE_1_URL": "/services/seo-optimization",
      RELATED_SERVICE_2: "Speed Optimization", "RELATED_SERVICE_2_URL": "/services/speed-optimization",
      RELATED_SERVICE_3: "WhatsApp Automation", "RELATED_SERVICE_3_URL": "/services/whatsapp-automation",
      RESULT_1: "+150% Growth", "RESULT_2": "2x Efficiency", "RESULT_3": "99.9% Uptime",
      CASE_STUDY_CLIENT: "Gujarat Enterprise", "CASE_STUDY_PROBLEM": "Struggling with manual " + s.name + " processes.", "CASE_STUDY_RESULT": "Automated 80% of workflow.",
      FAQ_1_Q: "How do we start?", "FAQ_1_A": "Simply contact us via WhatsApp or the form to book a consultation.",
      FAQ_2_Q: "Is this suitable for small biz?", "FAQ_2_A": "Yes, we have packages tailored for startups and SMBs.",
      FAQ_3_Q: "Do you provide support?", "FAQ_3_A": "Yes, we offer dedicated post-launch support for all projects.",
      FAQ_4_Q: "What is the timeline?", "FAQ_4_A": "Most projects are completed within 2-4 weeks.",
      FAQ_5_Q: "Can I customize the features?", "FAQ_5_A": "Absolutely, we build custom solutions based on your needs.",
      CTA_HEADLINE: "Ready to Master " + s.name + "?", "CTA_SUB": "Join 100+ successful businesses in Ahmedabad.",
      PRICING_ANCHOR: "Starting from ₹15,000",
      BUNDLE_PARENT: null,
      META_TITLE: s.name + " Services in Ahmedabad | DesiDevloper.com",
      META_DESC: "Expert " + s.name + " in Ahmedabad, Gujarat. Professional, fast, and results-driven. DesiDevloper.com — Your digital growth partner.",
      META_KEYWORDS: s.name + " Ahmedabad, " + s.name + " Gujarat, digital agency India",
      SERVICE_SCHEMA_JSON: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Service",
        "name": s.name,
        "provider": {
          "@type": "LocalBusiness",
          "name": "DesiDevloper.com",
          "address": {
            "@type": "PostalAddress",
            "addressLocality": "Ahmedabad",
            "addressRegion": "Gujarat",
            "addressCountry": "IN"
          }
        }
      })
    };
  });

  fs.writeFileSync(path.join(process.cwd(), 'data/services-data.json'), JSON.stringify(fullData, null, 2));
  console.log("Successfully generated 99 services in data/services-data.json");
};

generateData();
